name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Pacotes principais do seu app (atualizados)
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  intl: ^0.20.2  # <-- Atualizado
  cupertino_icons: ^1.0.8
  camera: ^0.11.3  # <-- Atualizado
  permission_handler: ^12.0.1  # <-- Atualizado
  sensors_plus: ^7.0.0  # <-- Atualizado
  vibration: ^3.1.4  # <-- ATUALIZADO (Este Ã© o que causa o erro)
  geolocator: ^14.0.2  # <-- Atualizado
  geocoding: ^4.0.0  # <-- Atualizado
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # <-- Atualizado

flutter:
  uses-material-design: true